#ifndef CONST_HPP
#define CONST_HPP
#include<string>

enum OPERATOR {
    COMMA,
    RETURN,
    FUNCTION, ENDFUNCTION,
    LSQRBRACKET, RSQRBRACKET, SIZE,
    IF, THEN,
    ELSE, ENDIF,
    WHILE, ENDLOOP, ENDWHILE,
    GOTO, COLON,
    LBRACKET, RBRACKET,
    ASSIGN,
    OR,
    AND,
    BITOR,
    XOR,
    BITAND,
    EQ, NEQ,
    LEQ, LT,
    GEQ, GT,
    SHL, SHR,
    PLUS, MINUS,
    MULT, DIV, MOD,
    DEF, FED
};

enum ERRORS {
	ERR_UNDEFINED_OPERATOR,
	ERR_WITH_GOTO_OR_LABELS,
	ERR_NOT_BALANCED_BRACKETS,
	ERR_NOT_BALANCED_FUNCTION,
	ERR_NOT_BALANCED_CONDITIONAL_OPERATORS,
	ERR_NAME_FUNCTION,
	ERR_FUNCTION_START_VARS,
	ERR_WITH_CONDITIONAL_OPERATORS,
	ERR_UNDEFINED_MAIN,
	ERR_UNDEFINED_VARIABLE,
	ERR_UNDEFINED_FUNCTION,
	ERR_ASSIGN_PROBLEMS,
	ERR_NO_COLONS_IN_CONDITION,
	ERR_WRONG_POSITION_FUNCTION,
	INVALID_SYNTAX,
	ERR_VOID_FUNCTION_IN_EVALUATION
};

enum {UNDEFINED = -INT32_MAX};

enum {FUNCTION_RETURN = -1};

extern int PRIORITY[];

extern std::string OPERTEXT[];

extern bool DEBUG;

extern bool INTERACTIVE;

extern int OPER_OR_VAR[];

extern std::string ERRORTEXT[];

extern int OPER_NUMBER;

#endif
